// Fs.Cpp.Com.idl : IDL source for Fs.Cpp.Com
//

// This file will be processed by the MIDL tool to
// produce the type library (FsCppCom.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(81990630-ee52-4fdd-866b-e30467eba092),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IApplication : IDispatch
{
};
[
	uuid(9086deb6-7e20-410d-be46-9efcd27eab53),
	version(1.0),
]
library FsCppComLib
{
	importlib("stdole2.tlb");
	[
		uuid(08c5e710-fcfe-40a9-9d8b-5e624bef3a3e)
	]
	coclass Application
	{
		[default] interface IApplication;
	};
};

import "shobjidl.idl";
